"""initial_schema

Revision ID: 3db6f6e197cf
Revises: 
Create Date: 2026-07-04 17:19:43.834646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db6f6e197cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_fetch_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trader_schema'
    )
    op.create_table('holiday_master',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date'),
    schema='trader_schema'
    )
    op.create_table('signal_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('price_at_signal', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('return_3d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_5d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_10d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('return_20d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'signal_date', 'signal_type', name='uq_signal_code_date_type'),
    schema='trader_schema'
    )
    op.create_table('signal_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('avg_return', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('median_return', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('std_return', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_type', 'industry', 'period', name='uq_stats_type_industry_period'),
    schema='trader_schema'
    )
    op.create_table('stock_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('isDelisted', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='trader_schema'
    )
    op.create_table('stock_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('is_delisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='trader_schema'
    )
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ma5', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ma25', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ma75', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('macd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bb_middle', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('volume_ma20', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date', name='uq_tech_code_date'),
    schema='trader_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_indicators', schema='trader_schema')
    op.drop_table('stock_price', schema='trader_schema')
    op.drop_table('stock_master', schema='trader_schema')
    op.drop_table('signal_stats', schema='trader_schema')
    op.drop_table('signal_history', schema='trader_schema')
    op.drop_table('holiday_master', schema='trader_schema')
    op.drop_table('batch_fetch_log', schema='trader_schema')
    # ### end Alembic commands ###
